import './globals.css';
import { Open_Sans } from 'next/font/google';
import Navbar from '@/components/Navbar';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={openSans.className}>
      <body className='mx-auto w-full max-w-screen-xl overflow-auto'>
        <header className='sticky top-0 z-10 border-b bg-white'>
          <Navbar />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
